weather:
  url: http://api.openweathermap.org/data/2.5/weather
  token: 88be56067214c953b2e277c0948327d1

postgres:
  database: admindb
  user: admin
  password: adminadmin
  host: localhost
  port: 5432
